dynawo/dynaflow-launcher

- sources/Algo/CMakeLists.txt
- sources/Algo/include/Algo.h
- sources/Algo/src/Algo.cpp
- sources/CMakeLists.txt
- sources/Context.cpp
- sources/Context.h
- sources/Inputs/include/NetworkManager.h
- sources/Inputs/include/Node.h
- sources/Inputs/src/NetworkManager.cpp
- tests/CMakeLists.txt
- tests/algo/CMakeLists.txt
- tests/algo/TestAlgo.cpp
- tests/inputs/TestNetworkManager.cpp
Put algorithms in their own library in order to test them independently
> Add algo library

- CMakeLists.txt
- README.md
Use cache for localization at build
Correct prefix path for all users
Generate doxygen doc with target "all" and install it
> Add minor improvements

- cmake/TestMain.cmake
- tests/main/CMakeLists.txt
- tests/main/reference/launch_infinite/outputIIDM.xml
Update output reference due to dynawo modification
> Add file comparaison to main tests

- sources/Outputs/src/Dyd.cpp
- tests/outputs/reference/TestDyd/TestDyd.dyd
> fix generators with diagram lib name

- etc/DFLMessages_en_GB.dic
- sources/Common/include/Log.h
- sources/Common/src/Log.cpp
- sources/Context.h
- sources/main.cpp
> #31 Append to log file after simulation ended

- sources/Algo/src/Algo.cpp
- sources/Common/include/Dico.h
- sources/Common/src/Dico.cpp
- sources/Context.cpp
- sources/Outputs/include/Dyd.h
- sources/main.cpp
- tests/inputs/TestNetworkManager.cpp
required to run in the distant machine
> Add corrections for remote compiling on centos 7.8

- sources/Algo/include/Algo.h
- sources/Algo/src/Algo.cpp
- sources/Context.cpp
- sources/Inputs/include/Configuration.h
- sources/Inputs/src/Configuration.cpp
- tests/algo/TestAlgo.cpp
- tests/algo/config.json
- tests/inputs/TestConfig.cpp
- tests/inputs/res/config.json
- tests/main/reference/launch/outputIIDM.xml
- tests/main/reference/launch_infinite/outputIIDM.xml
Signed-off-by: Guillaume Pernin <guillaume.pernin@rte-france.com>
> Loads: add criteria for loads library choice

- sources/Inputs/src/NetworkManager.cpp
> fix objects connections and topology

- etc/solver.par
- tests/main/reference/launch/outputIIDM.xml
- tests/main/reference/launch_infinite/outputIIDM.xml
> 55 modify solver parameters

- tests/main/reference/special_characters/outputIIDM.xml
> Update test reference for special characters

- sources/Outputs/src/Par.cpp
- tests/main/reference/launch/outputIIDM.xml
- tests/main/reference/launch_infinite/outputIIDM.xml
- tests/main/reference/special_characters/outputIIDM.xml
- tests/outputs/reference/TestPar/TestPar.par
Fixes #63 
test modifications are due to dynawo libraries update
> Correct parameter names in par files

- etc/DFLMessages_en_GB.dic
- sources/Inputs/include/Configuration.h
- sources/Inputs/src/Configuration.cpp
- sources/main.cpp
Correct the following errors:
- "dictionnary not found" error message cannot use dictionnary message, only cerr message
- comments
- styling
> Correct minor errors, styling and comments

- sources/Common/include/Message.hpp
- tests/algo/TestAlgo.cpp
- tests/common/TestMessage.cpp
Fixes #66 
We removed the dico configuration in algo test in order to not confuse a future developer with it and focus only on testing algo library
> Correct messages

- CPPLINT.cfg
- sources/Context.cpp
- sources/Outputs/include/Job.h
- sources/Outputs/src/Job.cpp
- tests/main/reference/launch/outputIIDM.xml
- tests/main/reference/launch_P/outputIIDM.xml
- tests/main/reference/launch_infinite/outputIIDM.xml
- tests/main/reference/special_characters/outputIIDM.xml
Also update tests references, as majority has the same results (see #76 )
> Improve debug testing

- sources/Inputs/include/NetworkManager.h
- sources/Inputs/src/NetworkManager.cpp
> Update with slack node API of dynawo

- sources/Outputs/src/Par.cpp
- tests/outputs/reference/TestParHvdc/TestParHvdc.par
The Dynawo PR related to issue 1348 must be merged before this DFL PR.
> Update HVDC parameters following dynawo issue 1348

- sources/Algo/include/Algo.h
- sources/Algo/src/Algo.cpp
- sources/Context.cpp
- sources/Inputs/include/NetworkManager.h
- sources/Inputs/include/Node.h
- sources/Inputs/src/NetworkManager.cpp
- sources/Inputs/src/Node.cpp
- tests/algo/TestAlgo.cpp
- tests/inputs/TestNetworkManager.cpp
- tests/inputs/TestNode.cpp
- tests/outputs/TestDyd.cpp
closes #80
closes #79
depends on dynawo PR 1346
> Use dynawo service manager to manage generators connected by switches

- sources/Algo/include/Algo.h
- sources/Algo/src/Algo.cpp
- sources/Inputs/include/Behaviours.h
- sources/Inputs/src/NetworkManager.cpp
- sources/Outputs/include/Constants.h
- sources/Outputs/include/Par.h
- sources/Outputs/src/Dyd.cpp
- sources/Outputs/src/Par.cpp
- tests/algo/TestAlgo.cpp
- tests/main/reference/launch/outputIIDM.xml
- tests/outputs/TestDiagram.cpp
- tests/outputs/TestDyd.cpp
- tests/outputs/TestPar.cpp
- tests/outputs/reference/TestDyd/TestDyd.dyd
- tests/outputs/reference/TestPar/TestPar.par
- tests/outputs/reference/TestParHvdc/TestParHvdc.par
closes #84 #87 
Signed-off-by: Guillaume Pernin <guillaume.pernin@rte-france.com>
> Target_ajustements: initial commit

- sources/Algo/src/Algo.cpp
- sources/Inputs/src/NetworkManager.cpp
- sources/Outputs/src/Dyd.cpp
- tests/algo/TestAlgo.cpp
- tests/main/CMakeLists.txt
- tests/main/reference/hvdc/outputIIDM.xml
- tests/main/res/TestIIDM_hvdc.iidm
- tests/main/res/config_hvdc.json
closes #97 
based of Dynawo's master
Signed-off-by: Guillaume Pernin <guillaume.pernin@rte-france.com>
> Hvdc_bug: fixed bug

- cmake/TestMain.cmake
- scripts/diff.py
- tests/main/CMakeLists.txt
> Add smart diff

- sources/Outputs/src/Dyd.cpp
- tests/outputs/reference/TestDyd/TestDyd.dyd
- tests/outputs/reference/TestDydHvdc/TestDydHvdc.dyd
- tests/outputs/reference/TestDydRemote/TestDydRemote.dyd
This PR can be merged once the dynawo PR linked to issue 1421 is accepted.
> Update following OS 1421

- sources/Outputs/src/Dyd.cpp
- tests/outputs/reference/TestDyd/TestDyd.dyd
- tests/outputs/reference/TestDydHvdc/TestDydHvdc.dyd
- tests/outputs/reference/TestDydRemote/TestDydRemote.dyd
> changing load model

- README.md
- scripts/hooks/commit_hook.sh
- scripts/set_commit_hook.sh
> #138 Add script to update git hook

- scripts/updateMainReference.py
> #137 Add script to update MAIN test references

- sources/Outputs/CMakeLists.txt
- sources/Outputs/include/Constants.h
- sources/Outputs/src/Constants.cpp
> Correct name diagram filename

- .gitignore
- README.md
- scripts/envDFL.sh
> #140 Add sript to compile and launch DFL

- sources/Outputs/src/Dyd.cpp
- tests/outputs/reference/TestDyd/TestDyd.dyd
- tests/outputs/reference/TestDydHvdc/TestDydHvdc.dyd
- tests/outputs/reference/TestDydRemote/TestDydRemote.dyd
This PR can be merged only when the OS 1621 in dynawo is merged
> Update following OS 1621

- CMakeLists.txt
- sources/main.cpp
closes #153 
linked to dynawo PR 1627: https://github.com/dynawo/dynawo/pull/1627
> #153 Use new dynawo API

- scripts/diff.py
- scripts/updateMainReference.py
> #159 Update scripts

- scripts/envDFL.sh
- scripts/set_commit_hook.sh
> #167 Correct scripts

- sources/Context.cpp
- sources/Context.h
- sources/Inputs/include/Configuration.h
- sources/Inputs/include/NetworkManager.h
- sources/Inputs/src/Configuration.cpp
- sources/Inputs/src/NetworkManager.cpp
- sources/Outputs/include/Par.h
- sources/Outputs/src/Par.cpp
- sources/main.cpp
> #169 Improve filepath management

- sources/Context.cpp
- sources/main.cpp
> #175 Correct some comments

- sources/main.cpp
> #179 Remove use of deprecated boost timer

- README.md
- scripts/envDFL.sh
- scripts/set_commit_hook.sh
> #172 Add formatting check before commit

- scripts/envDFL.sh
- tests/inputs/CMakeLists.txt
- tests/main/CMakeLists.txt
- tests/outputs/CMakeLists.txt
> #184 Correct DFL environement

- etc/DFLMessages_en_GB.dic
- sources/Algo/include/Algo.h
- sources/Algo/src/Algo.cpp
- sources/Context.cpp
- sources/Context.h
- sources/Inputs/include/Node.h
- sources/Inputs/src/NetworkManager.cpp
- sources/Inputs/src/Node.cpp
- sources/Outputs/include/Par.h
- sources/Outputs/src/Par.cpp
- tests/algo/TestAlgo.cpp
- tests/algo/TestAlgoDynModel.cpp
- tests/inputs/TestNode.cpp
- tests/outputs/TestPar.cpp
> #164 Process ref elements with active season

- sources/Outputs/include/Job.h
- sources/Outputs/src/Job.cpp
> #188 Correct export of job file

- sources/Context.cpp
> #195 Correct filtering automatons

- CMakeLists.txt
> #198 Fix conflict between local and deploy boost

- tests/CMakeLists.txt
> #115 Download googletest when not found

- tests/inputs/res/config.json
> #203 Correct tests

- sources/Algo/src/Algo.cpp
- sources/Common/src/Options.cpp
- sources/Context.cpp
- sources/Context.h
- sources/Inputs/include/NetworkManager.h
- sources/Inputs/src/NetworkManager.cpp
- sources/Outputs/include/Dyd.h
- sources/Outputs/include/Job.h
- sources/Outputs/include/Par.h
- sources/Outputs/src/Dyd.cpp
- sources/Outputs/src/Job.cpp
- sources/Outputs/src/Par.cpp
> #206 Improve coding and style

- sources/Outputs/include/Dyd.h
> #122 Fix old compiler compilation

- scripts/envDFL.sh
> #213 Fix error message in script

- sources/Outputs/src/Job.cpp
- tests/outputs/TestJob.cpp
closes #225 
requires https://github.com/dynawo/dynawo/pull/1936
> #225 Update JOB API

- scripts/envDFL.sh
> #245 fix ld library path

- scripts/envDFL.sh
> #247 Clean test results directory when cleaning build

- tests/main/CMakeLists.txt
- tests/main/reference/launch_slack/outputIIDM.xml
- tests/main/res/TestIIDM_launch_slack.iidm
- tests/main/res/config_launch_slack.json
requires dynawo/dynawo#1915
closes #235
> #235 Add test using XML slack terminal extension

- sources/Outputs/src/Dyd.cpp
- sources/Outputs/src/Par.cpp
- tests/outputs/reference/TestDyd/TestDyd.dyd
- tests/outputs/reference/TestPar/TestPar.par
> #256 update svarc lib following OS 1897

- sources/Outputs/src/Par.cpp
- tests/main/reference/hvdc/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPQProp/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPQPropSwitch/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPQProp_diagrams/outputIIDM.xml
- tests/main/reference/hvdc_diagrams/outputIIDM.xml
- tests/main/res/TestIIDM_hvdc.iidm
- tests/main/res/TestIIDM_hvdc_HvdcPQProp.iidm
- tests/main/res/TestIIDM_hvdc_HvdcPQPropSwitch.iidm
- tests/main/res/TestIIDM_hvdc_HvdcPQProp_diagrams.iidm
- tests/main/res/TestIIDM_hvdc_HvdcPVDangling_HvdcPTanPhiDangling.iidm
- tests/main/res/TestIIDM_hvdc_HvdcPVDangling_HvdcPTanPhiDangling_diagrams.iidm
- tests/main/res/TestIIDM_hvdc_HvdcPV_HvdcPTanPhi.iidm
- tests/main/res/TestIIDM_hvdc_HvdcPV_HvdcPTanPhi_diagrams.iidm
- tests/main/res/TestIIDM_hvdc_dangling.iidm
- tests/main/res/TestIIDM_hvdc_diagrams.iidm
- tests/main_sa/res/TestIIDM_launch.iidm
- tests/outputs/reference/TestParHvdc/TestParHvdc.par
OS 1898 must be merged before this
> #222 Update following OS 1898

- .github/workflows/ci.yml
- .github/workflows/tools.sh
- CMakeLists.txt
- scripts/checkContingencies.py
- scripts/envDFL.sh
> #15 continuous integration using github workflows

- sources/Algo/include/GeneratorDefinitionAlgorithm.h
- sources/Algo/include/HVDCDefinitionAlgorithm.h
- sources/Algo/include/SVarCDefinitionAlgorithm.h
- sources/Algo/src/ContingencyValidationAlgorithm.cpp
- sources/Algo/src/GeneratorDefinitionAlgorithm.cpp
- sources/Algo/src/HVDCDefinitionAlgorithm.cpp
- sources/Algo/src/MainConnexComponentAlgorithm.cpp
- sources/Outputs/include/Constants.h
> #301 fix sonar code smells

- scripts/checkContingencies.py
> #306 fix python script not to check SA timeline in release mode

- .github/workflows/ci.yml
- README.md
- scripts/envDFL.sh
> #311 automatically open test coverage summary when running it

- sources/Outputs/src/Job.cpp
- tests/outputs/TestJob.cpp
- tests/outputs/reference/TestJob/TestJob_debug.jobs
- tests/outputs/reference/TestJob/TestJob_release.jobs
> #316 fix exported job

- sources/Common/CMakeLists.txt
> #309 copy dictionaries only when different

- scripts/envDFL.sh
> #321 add dynaflow_launcher_python_command in envDFL

- sources/Algo/include/DynModelDefinitionAlgorithm.h
- sources/Algo/src/DynModelDefinitionAlgorithm.cpp
- sources/Context.cpp
- tests/algo/TestAlgoDynModel.cpp
- tests/main/CMakeLists.txt
- tests/main/reference/no_SVC_regulation/outputIIDM.xml
- tests/main/res/TestIIDM_no_SVC_regulation.iidm
- tests/main/res/config_no_SVC_regulation.json
> #217 complete options

- sources/Inputs/src/NetworkManager.cpp
> #327 fix bus id retrieval when a battery is present

- sources/Algo/src/LoadDefinitionAlgorithm.cpp
- sources/Inputs/include/Behaviours.h
- sources/Inputs/src/NetworkManager.cpp
- tests/algo/TestAlgo.cpp
> #345 when a load is fictitous, associate a network model

- scripts/envDFL.sh
> #341 fails with an explicit error when dynawo-core was compiled with legacy iidm library

- .gitignore
- CMakeLists.txt
- cmake/getgitheadrevision.cmake
- cmake/version.h.in
- sources/CMakeLists.txt
- sources/Inputs/src/DynamicDataBaseManager.cpp
- sources/main.cpp
> #350 Add the git hash to the log header

- sources/Inputs/include/Configuration.h
- sources/Inputs/src/Configuration.cpp
- tests/inputs/TestConfig.cpp
- tests/inputs/res/config.json
> #336 remove unused parameter PSTRegulationOn

- CMakeLists.txt
requires:
- https://github.com/dynawo/dynawo/pull/2040
- https://github.com/dynawo/dynawo-algorithms/pull/132
closes #254
> #254 Remove cpp98 compilation artefacts

- .github/pull_request_template.md
> #369 add pull request template

- CMakeLists.txt
> #367 v1.4.0

- documentation/dynaflow_launcher_documentation.sh
> #315 fix version on master

- scripts/dynaflow-launcher.sh
- scripts/envDFL.sh
> #378 improve parsing to handle option=value syntax

- scripts/dynaflow-launcher.sh
- scripts/envDFL.sh
> #378 parsing v13

- .github/workflows/ci.yml
- .github/workflows/nightly-release.yml
> 380 nightly workflow

- tests/CMakeLists.txt
> #381 Fix gtest target with debug.

- cmake/FindGMock.cmake
> #381 Fix find_package gmock to handle debug libraries.

- cmake/FindGMock.cmake
> 381 gmock v13

- scripts/dynaflow-launcher.sh
- sources/main.cpp
> #395 Add sha1 in version output.

- scripts/dynaflow-launcher.sh
- sources/main.cpp
> 395 version sha1 v13

- scripts/dynaflow-launcher.sh
> #403 fix iidm extension env var when private iidm lib is available

- documentation/configuringDynaflowLauncher/DynaflowLaunchersInputFiles.tex
- documentation/functionalDoc/functionalDoc.tex
- documentation/resources/syntaxExample/config.json
- documentation/resources/syntaxExample/solver.par
- sources/Context.cpp
- sources/Inputs/include/Configuration.h
- sources/Inputs/src/Configuration.cpp
- sources/Outputs/CMakeLists.txt
- sources/Outputs/include/Constants.h
- sources/Outputs/include/Solver.h
- sources/Outputs/src/Solver.cpp
- tests/inputs/TestConfig.cpp
- tests/inputs/res/config.json
- tests/outputs/CMakeLists.txt
- tests/outputs/TestSolverPar.cpp
- tests/outputs/reference/TestSolverPar/solver.par
- tests/outputs/reference/TestSolverParDefault/solver.par
- tests/outputs/res/config_solver.json
- tests/outputs/res/config_solver_default.json
> 407 add timestep choice in config

- documentation/functionalDoc/functionalDoc.tex
- sources/Algo/include/HVDCDefinitionAlgorithm.h
- sources/Algo/src/HVDCDefinitionAlgorithm.cpp
- sources/Inputs/include/HvdcLine.h
- sources/Inputs/src/HvdcLine.cpp
- sources/Inputs/src/NetworkManager.cpp
- sources/Outputs/include/ParHvdc.h
- sources/Outputs/src/DydHvdc.cpp
- sources/Outputs/src/ParHvdc.cpp
- tests/algo/TestAlgo.cpp
- tests/inputs/TestNetworkManager.cpp
- tests/outputs/TestDiagram.cpp
- tests/outputs/TestDyd.cpp
- tests/outputs/TestPar.cpp
- tests/outputs/reference/TestParHvdc/TestParHvdc.par
> #409 Adapt hvdc model choice using hvdc model without p0 recalculation

- sources/CMakeLists.txt
- sources/Context.cpp
- sources/Context.h
- sources/main.cpp
> #396 Ouput slack node in separate file.

- sources/CMakeLists.txt
- sources/Context.cpp
- sources/Context.h
- sources/main.cpp
> 396 slack node v13

- sources/Outputs/src/ParHvdc.cpp
- tests/outputs/reference/TestParHvdc/TestParHvdc.par
> #430 update hvdc par following OS 2374

- tests/main_sa/reference/launch/hvdcline_contingency/lostEquipments.xml
- tests/main_sa/reference/launch/hvdcline_contingency/outputIIDM.xml
- tests/main_sa/reference/launch/static_var_compensator_contingency/lostEquipments.xml
- tests/main_sa/reference/launch/static_var_compensator_contingency/outputIIDM.xml
> #434 update tests following OS 2439

- sources/Outputs/include/Job.h
> Temporary fix on output iidm file not generated.

- tests/outputs/TestJob.cpp
- tests/outputs/reference/TestJob/TestJob_release.jobs
- tests/outputs/reference/TestJobPrecision/TestJobPrecision_release.jobs
> #428 fix unit tests after temporary fix

- tests/main_sa/reference/launch/hvdcline_contingency/lostEquipments.xml
- tests/main_sa/reference/launch/static_var_compensator_contingency/lostEquipments.xml
> #434 fix unit tests

- tests/main_sa/reference/launch/hvdcline_contingency/lostEquipments.xml
- tests/main_sa/reference/launch/static_var_compensator_contingency/lostEquipments.xml
> #434 fix unit tests references

- tests/main_sa/reference/launch/two_windings_transformer_open_ended/outputIIDM.xml
> 402 fix ut

- tests/main/reference/distant_regulation/outputIIDM.xml
> #451 update iidm reference after 2489 OS

- tests/main/reference/distant_regulation/outputIIDM.xml
> #451 fix load data itf v13

- tests/main_sa/reference/launch/busbarsection_contingency/lostEquipments.xml
- tests/main_sa/reference/launch/generator_contingency/lostEquipments.xml
- tests/main_sa/reference/launch/generator_network_contingency/lostEquipments.xml
- tests/main_sa/reference/launch/hvdcline_contingency/lostEquipments.xml
- tests/main_sa/reference/launch/line_contingency_open_ended/lostEquipments.xml
- tests/main_sa/reference/launch/load_contingency/lostEquipments.xml
- tests/main_sa/reference/launch/shunt_compensator_contingency/lostEquipments.xml
- tests/main_sa/reference/launch/static_var_compensator_contingency/lostEquipments.xml
- tests/main_sa/reference/launch/static_var_compensator_network_contingency/lostEquipments.xml
- tests/main_sa/reference/launch/two_windings_transformer_open_ended/lostEquipments.xml
Follows https://github.com/dynawo/dynawo/pull/2420
closes #454
> #454 update references following 1933 OS

- .github/workflows/release.yml
> #477 Fix release workflow.

- .github/workflows/release.yml
> 477 fix release workflow v13

- sources/main.cpp
> #395 Fix print of sha1 in version.

- .github/workflows/release.yml
> #477 Fix release workflow 2.

- README.md
- documentation/README.md
- documentation/installation/installation.tex
> #483 update documentation links to 1.3.1

- etc/Dictionaries/DFLError_en_GB.dic
- sources/Inputs/src/Configuration.cpp
> #413 Fix for Centos7

- sources/main.cpp
> #401 fix centos7 build

- sources/Algo/src/GeneratorDefinitionAlgorithm.cpp
- tests/main/reference/hvdc/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPQProp/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPQPropDangling/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPQPropDangling_diagrams/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPQPropSwitch/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPQProp_diagrams/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPVDangling_HvdcPTanPhiDangling/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPVDangling_HvdcPTanPhiDangling_diagrams/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPV_HvdcPTanPhi/outputIIDM.xml
- tests/main/reference/hvdc_dangling/outputIIDM.xml
- tests/main/reference/hvdc_diagrams/outputIIDM.xml
- tests/main/reference/hvdc_diagrams_flat_start/outputIIDM.xml
- tests/main/reference/no_SVC_regulation/outputIIDM.xml
- tests/main_n_sa/reference/launch/busbarsection_contingency/outputIIDM.xml
- tests/main_n_sa/reference/launch/generator_contingency/outputIIDM.xml
- tests/main_n_sa/reference/launch/three_windings_transformer_contingency/outputIIDM.xml
- tests/main_n_sa/reference/launch/two_windings_transformer_contingency/outputIIDM.xml
- tests/main_sa/reference/launch/dangling_line_contingency/outputIIDM.xml
- tests/main_sa/reference/launch/generator_contingency/constraints.xml
> #491 fix generator algorithm when model is with tfo

- README.md
> #495 update readme

- sources/main.cpp
> #500 fix config read in main when outputDir is not specified

- README.md
> #450 add an example of sa and nsa in readme

- sources/Algo/include/GeneratorDefinitionAlgorithm.h
- sources/Algo/src/GeneratorDefinitionAlgorithm.cpp
- sources/Inputs/include/Behaviours.h
- sources/Inputs/src/NetworkManager.cpp
- sources/Outputs/include/OutputsConstants.h
- sources/Outputs/include/ParCommon.h
- sources/Outputs/include/ParGenerator.h
- sources/Outputs/src/ParGenerator.cpp
- tests/main/reference/hvdc/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPQProp/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPQPropSwitch/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPQProp_diagrams/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPV_HvdcPTanPhi/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPV_HvdcPTanPhi_diagrams/outputIIDM.xml
- tests/main/reference/hvdc_diagrams/outputIIDM.xml
- tests/main/reference/hvdc_diagrams_flat_start/outputIIDM.xml
- tests/outputs/TestPar.cpp
- tests/outputs/reference/TestPar/TestPar.par
> #494 dump specific transformer parameters for nuclear generators

- .github/workflows/release.yml
> #541 Add centos7 distribution generation.

- etc/Dictionaries/DFLError_en_GB.dic
- etc/Dictionaries/DFLLog_en_GB.dic
- sources/Common/include/Log.h
- sources/Context.cpp
- sources/Inputs/src/AssemblingDataBase.cpp
- sources/Inputs/src/SettingDataBase.cpp
> #544 Avoid a crash when no slack node was found

- .github/workflows/ci.yml
- .github/workflows/nightly-release.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .github/workflows/tools.sh
> #539 Fix workflow curl calls and add token.

- .github/workflows/ci.yml
- .github/workflows/nightly-release.yml
> 380 nightly workflow v14

- sources/Outputs/include/ParCommon.h
- sources/Outputs/src/DydGenerator.cpp
- tests/Tests.cpp
- tests/main/reference/hvdc/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPQProp/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPQPropDangling/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPQPropDangling_diagrams/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPQPropSwitch/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPQProp_diagrams/outputIIDM.xml
- tests/main/reference/hvdc_diagrams/outputIIDM.xml
- tests/main/reference/hvdc_diagrams_flat_start/outputIIDM.xml
- tests/outputs/reference/TestDydRemote/TestDydRemote.dyd
- tests/outputs/reference/TestParHvdc/TestParHvdc.par
- tests/outputs/reference/TestParRemote/TestParRemote.par
- tests/outputs/reference/TestStartingPointMode/TestStartingPointModeFlatNoIRL.par
- tests/outputs/reference/TestStartingPointMode/TestStartingPointModeFlatWithIRL.par
- tests/outputs/reference/TestStartingPointMode/TestStartingPointModeWarmNoIRL.par
- tests/outputs/reference/TestStartingPointMode/TestStartingPointModeWarmWithIRL.par
> #526 update dyd and par creation following OS 2673

- .github/workflows/nightly-release.yml
> #380 Fix name of version and version use for branch name in workflow.

- tests/main_n_sa/reference/launch/three_windings_transformer_contingency/lostEquipments.xml
- tests/main_sa/reference/launch/three_windings_transformer_contingency/lostEquipments.xml
> #549 NRT references update

- .github/workflows/ci.yml
- .github/workflows/nightly-release.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .github/workflows/tools.sh
> #539 Update api to use token in workflow and avoid github limite rate.

- README.md
- documentation/README.md
- documentation/installation/installation.tex
- documentation/introduction/introduction.tex
> #560 update documentation links to v1.4.0 assets

- .github/workflows/ci.yml
- .github/workflows/nightly-release.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- CMakeLists.txt
- documentation/dynaflow_launcher_documentation.sh
> #561 v1.4.1

- tests/main/res/assembling_phase_shifter.xml
- tests/main/res/setting_phase_shifter.xml
> #555 Update following OS 2737

- scripts/dynaflow-launcher.sh
> #564 use mpi from dfl installation instead of system mpi

- scripts/envDFL.sh
> #528 remove sanity check about legacy iidm

- scripts/checkContingencies.py
> #575 NRT update

- scripts/checkContingencies.py
- scripts/diffContingencies.py
- scripts/envDFL.sh
> #583 Update tests following 327 from dyn-algos.

- sources/Context.cpp
> #579 exit when a partially connected automaton is deleted to avoid crash

- sources/Outputs/src/Job.cpp
- tests/main/reference/hvdc/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPQProp/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPQPropDangling/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPQPropDangling_diagrams/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPQPropSwitch/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPQProp_diagrams/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPVDangling_HvdcPTanPhiDangling/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPVDangling_HvdcPTanPhiDangling_diagrams/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPV_HvdcPTanPhi/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPV_HvdcPTanPhi_diagrams/outputIIDM.xml
- tests/main/reference/hvdc_dangling/outputIIDM.xml
- tests/main/reference/hvdc_diagrams/outputIIDM.xml
- tests/main/reference/hvdc_diagrams_flat_start/outputIIDM.xml
- tests/main/reference/hvdc_line_normal/outputIIDM.xml
- tests/main/reference/launch_diagram_tfo/outputIIDM.xml
- tests/main/reference/launch_svc/outputIIDM.xml
- tests/main/reference/launch_svc_infinite/outputIIDM.xml
- tests/main/reference/launch_svc_network/outputIIDM.xml
- tests/main/reference/launch_svc_tfo/outputIIDM.xml
- tests/main/reference/launch_svc_tfo_infinite/outputIIDM.xml
- tests/outputs/reference/TestJob/TestJob_debug.jobs
- tests/outputs/reference/TestJob/TestJob_release.jobs
- tests/outputs/reference/TestJob/TestJob_release_sa.jobs
> #570 align dynawo precision with solver precision to avoid numerical

- .github/workflows/nightly.yml
> #380 Fix name of tag in nightly for release branch.

- documentation/configuringDynaflowLauncher/DynaflowLaunchersInputFiles.tex
- documentation/resources/syntaxExample/config_SA.json
- etc/Dictionaries/DFLError_en_GB.dic
- sources/Inputs/include/Configuration.h
- sources/Inputs/src/Configuration.cpp
- sources/main.cpp
- tests/inputs/TestConfig.cpp
- tests/inputs/res/config_N.json
- tests/inputs/res/config_SA.json
- tests/inputs/res/config_SA_2.json
- tests/inputs/res/config_flat.json
> 476 nsa allow having a different configuration in the same json file for n and sa

- documentation/functionalDoc/functionalDoc.tex
- etc/xsd/assembling.xsd
- sources/Outputs/include/DydDynModel.h
- sources/Outputs/include/DydGenerator.h
- sources/Outputs/src/DydDynModel.cpp
- sources/Outputs/src/DydGenerator.cpp
- sources/Outputs/src/ParDynModel.cpp
- tests/algo/res/assembling.xml
- tests/algo/res/assembling_test_generator.xml
- tests/algo/res/assembling_test_generator_rpcl2.xml
- tests/main/res/assembling_svc.xml
- tests/outputs/reference/TestDyd/TestDyd.dyd
- tests/outputs/reference/TestDydDynModel/TestDydDynModel.dyd
- tests/outputs/reference/TestDydRemote/TestDydRemote.dyd
- tests/outputs/reference/TestParDynModel/TestParDynModel.par
- tests/outputs/res/assembling.xml
> #567 Use frozen capability of svc

- sources/Algo/include/GeneratorDefinitionAlgorithm.h
- sources/Algo/src/GeneratorDefinitionAlgorithm.cpp
- sources/Context.cpp
- sources/Context.h
- sources/Inputs/include/Behaviours.h
- sources/Inputs/src/NetworkManager.cpp
- sources/Outputs/include/Dyd.h
- sources/Outputs/include/DydGenerator.h
- sources/Outputs/include/Par.h
- sources/Outputs/include/ParGenerator.h
- sources/Outputs/src/Dyd.cpp
- sources/Outputs/src/DydDynModel.cpp
- sources/Outputs/src/DydGenerator.cpp
- sources/Outputs/src/Par.cpp
- sources/Outputs/src/ParDynModel.cpp
- sources/Outputs/src/ParGenerator.cpp
- tests/algo/TestAlgoDynModel.cpp
- tests/algo/TestContingencyAlgo.cpp
- tests/algo/TestGeneratorsAlgo.cpp
- tests/outputs/TestDiagram.cpp
- tests/outputs/TestDyd.cpp
- tests/outputs/TestPar.cpp
- tests/outputs/reference/TestParDynModel/TestParDynModel.par
- tests/outputs/reference/TestParRemote/TestParRemote.par
> #586 properly initialize frozen property of VRRemote and SVCs + renaming

- etc/Dictionaries/DFLLog_en_GB.dic
- sources/Algo/CMakeLists.txt
- sources/Algo/include/TransfoDefinitionAlgorithm.h
- sources/Algo/src/TransfoDefinitionAlgorithm.cpp
- sources/Context.cpp
- sources/Context.h
- sources/Inputs/include/Node.h
- sources/Inputs/src/NetworkManager.cpp
- sources/Inputs/src/Node.cpp
- sources/Outputs/include/Par.h
- sources/Outputs/include/ParDynModel.h
- sources/Outputs/src/Par.cpp
- sources/Outputs/src/ParDynModel.cpp
- tests/algo/TestAlgoDynModel.cpp
- tests/algo/TestContingencyAlgo.cpp
- tests/inputs/TestNode.cpp
- tests/outputs/TestPar.cpp
- tests/outputs/reference/TestParDynModel/TestParDynModel.par
- tests/outputs/res/assembling.xml
- tests/outputs/res/setting.xml
> #559 retrieve transformers active season when referenced in par

- sources/Outputs/src/ParHvdc.cpp
- tests/outputs/reference/TestParHvdc/TestParHvdc.par
- tests/outputs/reference/TestStartingPointMode/TestStartingPointModeFlatNoIRL.par
- tests/outputs/reference/TestStartingPointMode/TestStartingPointModeFlatWithIRL.par
- tests/outputs/reference/TestStartingPointMode/TestStartingPointModeWarmNoIRL.par
- tests/outputs/reference/TestStartingPointMode/TestStartingPointModeWarmWithIRL.par
> #599 Fix PRefSet0Pu

- sources/Outputs/include/OutputsConstants.h
- sources/Outputs/include/ParCommon.h
- sources/Outputs/include/ParGenerator.h
- sources/Outputs/src/ParDynModel.cpp
- sources/Outputs/src/ParGenerator.cpp
- tests/main/reference/launch_svc_tfo/outputIIDM.xml
- tests/main/reference/launch_svc_tfo_infinite/outputIIDM.xml
- tests/main/res/setting_svc.xml
- tests/outputs/reference/TestDydDynModel/TestDydDynModel.dyd
- tests/outputs/reference/TestParDynModel/TestParDynModel.par
- tests/outputs/res/setting.xml
> #592 use SNom from DDB for SVCs and generators in SVCs area

- sources/Outputs/include/OutputsConstants.h
- sources/Outputs/include/ParCommon.h
- sources/Outputs/include/ParGenerator.h
- sources/Outputs/src/ParDynModel.cpp
- sources/Outputs/src/ParGenerator.cpp
- tests/main/reference/launch_svc_tfo/outputIIDM.xml
- tests/main/reference/launch_svc_tfo_infinite/outputIIDM.xml
- tests/main/res/setting_svc.xml
- tests/outputs/reference/TestDydDynModel/TestDydDynModel.dyd
- tests/outputs/reference/TestParDynModel/TestParDynModel.par
- tests/outputs/res/setting.xml
> #592 use SNom from DDB for SVCs and generatrors in SVCs area

- past_commits.txt
> #604 add past_commits.txt file

- etc/Dictionaries/DFLError_en_GB.dic
- sources/Context.h
- sources/Inputs/include/AssemblingDataBase.h
- sources/Inputs/src/AssemblingDataBase.cpp
- sources/main.cpp
- tests/inputs/TestAssemblingXmlDocument.cpp
- tests/inputs/res/assembling_svc.xml
> #516 Throw an error if there is a SVC in flat starting point mode

- etc/Dictionaries/DFLError_en_GB.dic
- sources/Context.h
- sources/Inputs/include/AssemblingDataBase.h
- sources/Inputs/src/AssemblingDataBase.cpp
- sources/main.cpp
- tests/inputs/TestAssemblingXmlDocument.cpp
- tests/inputs/res/assembling_svc.xml
> 516 svc disable the svc if we use a flat start

- .clang-format
> #488 fix unified clang format

- sources/Algo/include/HVDCDefinitionAlgorithm.h
- sources/Algo/src/HVDCDefinitionAlgorithm.cpp
- sources/Outputs/src/Diagram.cpp
- sources/Outputs/src/ParHvdc.cpp
- tests/algo/TestHvdcLineAlgo.cpp
- tests/outputs/TestDiagram.cpp
- tests/outputs/TestDyd.cpp
- tests/outputs/TestPar.cpp
> #611 Do not duplicate VSC objects and fix testDiagram

- sources/Inputs/src/NetworkManager.cpp
- sources/Outputs/src/ParGenerator.cpp
- tests/algo/TestConnexityAlgo.cpp
- tests/algo/res/IEEE14_disconnected_shunts.iidm
- tests/inputs/TestNetworkManager.cpp
> #578 consider all calculated bus from a node as belonging to the main

- tests/main/reference/hvdc_HvdcPV_HvdcPTanPhi_diagrams/outputIIDM.xml
> #611 fix nrt

- sources/Context.cpp
- sources/Context.h
- sources/Inputs/include/Configuration.h
- sources/Inputs/src/Configuration.cpp
- sources/main.cpp
- tests/main/reference/launch_svc/outputIIDM.xml
- tests/main/reference/launch_svc_infinite/outputIIDM.xml
- tests/main/reference/launch_svc_network/outputIIDM.xml
- tests/main/reference/launch_svc_tfo/outputIIDM.xml
- tests/main/reference/launch_svc_tfo_infinite/outputIIDM.xml
> #514 Increase simulation time and event time when SVC are used

- sources/Outputs/src/OutputsConstants.cpp
> #27 fix nil uuid on centos7

- scripts/checkContingencies.py
- sources/Outputs/src/Job.cpp
- tests/outputs/TestJob.cpp
- tests/outputs/reference/TestJob/TestJob_debug.jobs
- tests/outputs/reference/TestJobPrecision/TestJobPrecision_debug.jobs
> #627 Ouput timeline in xml.

- scripts/checkContingencies.py
- sources/Outputs/src/Job.cpp
- tests/outputs/TestJob.cpp
- tests/outputs/reference/TestJob/TestJob_debug.jobs
- tests/outputs/reference/TestJobPrecision/TestJobPrecision_debug.jobs
> 627 timeline xml v1.4

- .github/workflows/ci.yml
- .github/workflows/nightly-release.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- CMakeLists.txt
- documentation/dynaflow_launcher_documentation.sh
> #632 v1.6.0

- scripts/checkContingencies.py
> #627 fix tests when parsing timeline xml files

- tests/CMakeLists.txt
> #27 Fix gtest target for recent cmake.

- README.md
- documentation/README.md
- documentation/installation/installation.tex
> #644 update links following v1.4.1 release

- sources/Outputs/src/Job.cpp
- tests/main/reference/distant_regulation/outputIIDM.xml
- tests/main/reference/launch_svc_tfo/outputIIDM.xml
- tests/main/reference/launch_svc_tfo_infinite/outputIIDM.xml
- tests/outputs/reference/TestJob/TestJob_debug.jobs
- tests/outputs/reference/TestJob/TestJob_release.jobs
- tests/outputs/reference/TestJob/TestJob_release_sa.jobs
> #652 Fix limUQDown and limUQUp calculation

- sources/Outputs/include/DydDynModel.h
- sources/Outputs/src/DydDynModel.cpp
- tests/outputs/reference/TestDydDynModel/TestDydDynModel.dyd
> #620 All the indexes of table start at 0

- sources/Outputs/src/ParDynModel.cpp
- tests/main/reference/launch_svc/outputIIDM.xml
- tests/main/reference/launch_svc_infinite/outputIIDM.xml
- tests/main/reference/launch_svc_network/outputIIDM.xml
- tests/main/reference/launch_svc_tfo/outputIIDM.xml
- tests/main/reference/launch_svc_tfo_infinite/outputIIDM.xml
- tests/outputs/reference/TestParDynModel/TestParDynModel.par
> #620 fix SVC parameters

- sources/Outputs/src/ParGenerator.cpp
> #659 Fix .par when Rpcl2 and rectangular diagram

- sources/Outputs/src/ParHvdc.cpp
- tests/outputs/reference/TestParHvdc/TestParHvdc.par
- tests/outputs/reference/TestStartingPointMode/TestStartingPointModeFlatNoIRL.par
- tests/outputs/reference/TestStartingPointMode/TestStartingPointModeFlatWithIRL.par
- tests/outputs/reference/TestStartingPointMode/TestStartingPointModeWarmNoIRL.par
- tests/outputs/reference/TestStartingPointMode/TestStartingPointModeWarmWithIRL.par
> #654 Update following OS 2592

- sources/Outputs/src/ParHvdc.cpp
> #654 make sure constant parameters have the good type

- sources/Outputs/src/ParHvdc.cpp
> #654 force cast of hvdc_QNom parameter to double

- documentation/functionalDoc/functionalDoc.tex
- etc/xsd/assembling.xsd
- sources/Algo/include/DynModelDefinitionAlgorithm.h
- sources/Algo/src/DynModelDefinitionAlgorithm.cpp
- sources/Inputs/include/AssemblingDataBase.h
- sources/Inputs/src/AssemblingDataBase.cpp
- sources/Outputs/include/Dyd.h
- sources/Outputs/include/DydDynModel.h
- sources/Outputs/src/DydDynModel.cpp
- tests/algo/TestAlgoDynModel.cpp
- tests/algo/res/assembling.xml
- tests/inputs/TestAssemblingXmlDocument.cpp
- tests/inputs/res/assembling.xml
- tests/outputs/TestDyd.cpp
- tests/outputs/reference/TestDydDynModel/TestDydDynModel.dyd
- tests/outputs/res/assembling.xml
> #649 add load single association in assembling

- .github/workflows/ci.yml
- .github/workflows/nightly-release.yml
- scripts/dynaflow-launcher.cmd
> #626 add CI for Windows

- .github/workflows/nightly-release.yml
> #668 enhance nightly release

- .github/workflows/nightly-release.yml
> #668 fix nightly release

- sources/Outputs/include/OutputsConstants.h
- sources/Outputs/include/ParDynModel.h
- sources/Outputs/src/ParDynModel.cpp
- tests/outputs/TestPar.cpp
- tests/outputs/reference/TestParDynModel/TestParDynModel.par
- tests/outputs/res/assembling.xml
- tests/outputs/res/setting.xml
closes #650
Signed-off-by: Florentine Rosiere <florentine.rosiere@rte-france.com>
> #650 add possibility to reference static id in parameters with macros

- sources/Outputs/CMakeLists.txt
- sources/Outputs/include/Dyd.h
- sources/Outputs/include/DydGenerator.h
- sources/Outputs/include/DydHvdc.h
- sources/Outputs/include/DydVRRemote.h
- sources/Outputs/include/Par.h
- sources/Outputs/include/ParGenerator.h
- sources/Outputs/include/ParVRRemote.h
- sources/Outputs/src/Dyd.cpp
- sources/Outputs/src/DydGenerator.cpp
- sources/Outputs/src/DydHvdc.cpp
- sources/Outputs/src/DydVRRemote.cpp
- sources/Outputs/src/Par.cpp
- sources/Outputs/src/ParGenerator.cpp
- sources/Outputs/src/ParHvdc.cpp
- sources/Outputs/src/ParVRRemote.cpp
- tests/outputs/TestDyd.cpp
- tests/outputs/TestPar.cpp
- tests/outputs/reference/TestDydRemote/TestDydRemote.dyd
- tests/outputs/reference/TestDydVRRemote/TestDydVRRemote.dyd
- tests/outputs/reference/TestParVRRemote/TestParVRRemote.par
> #630 Two VRRemote with same name are added when a node is regulated by several generators and a HVDC with vscs

- sources/Outputs/include/ParEvent.h
- sources/Outputs/src/DydEvent.cpp
- sources/Outputs/src/ParEvent.cpp
- tests/outputs/reference/TestDydEvent/TestDydEvent.dyd
- tests/outputs/reference/TestParEvent/TestParEvent.par
> #665 update of events following 2907 OS

- sources/Context.h
- sources/Inputs/include/NetworkManager.h
- sources/Outputs/src/Diagram.cpp
- sources/Outputs/src/Dyd.cpp
- sources/Outputs/src/Job.cpp
- sources/Outputs/src/Network.cpp
- sources/Outputs/src/Par.cpp
- sources/Outputs/src/Solver.cpp
> #672 Replace std::forward wrong usage by std::move in all the code

- .gitignore
- tests/CMakeLists.txt
> #682 Fix error with GTest:Main target not a library.

- .github/workflows/nightly-release.yml
> #449 Publish nightly doc

- sources/Context.cpp
> #673 Dynawo output files are not generated when simulation fails

- .github/workflows/nightly-release.yml
> #668 replace action with javascript

- .github/workflows/ci.yml
- .github/workflows/nightly-release.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
> #687 use lowercase 'v' for release version

- sources/Context.cpp
> #673 Windows include fix

- .github/workflows/nightly.yml
> #690 Start nightlies on repository dispatch

- sources/Outputs/src/ParDynModel.cpp
> #696 Settings: Handle CONNECTED_STATIC_ID in references

- documentation/configuringDynaflowLauncher/DynaflowLaunchersInputFiles.tex
- documentation/resources/syntaxExample/config.json
- tests/inputs/res/config_caseinsensitive.json
- tests/inputs/res/incorrect_config_2.json
> #699 remove numberOfThreads option from the documentation as it does not

- CMakeLists.txt
- documentation/dynaflow_launcher_documentation.sh
> #701 v1.5.1

- README.md
- documentation/README.md
- documentation/installation/installation.tex
- documentation/introduction/introduction.tex
> #703 update links and documentation following v1.5.0 release

- etc/Dictionaries/DFLLog_en_GB.dic
- sources/Algo/CMakeLists.txt
- sources/Algo/include/DynModelFilterAlgorithm.h
- sources/Algo/include/GeneratorDefinitionAlgorithm.h
- sources/Algo/src/DynModelFilterAlgorithm.cpp
- sources/Algo/src/GeneratorDefinitionAlgorithm.cpp
- sources/Context.cpp
- sources/Context.h
- tests/algo/CMakeLists.txt
- tests/algo/TestDynModelFilterAlgo.cpp
- tests/algo/res/assembling_svc.xml
> #680 Remove RPCL from generators regulated by partially connected SVCs

- documentation/introduction/introduction.tex
> #703 fix documentation compilation

- README.md
> Added Julien De Sloovere in the Readme

- scripts/envDFL.sh
- sources/Algo/src/DynModelDefinitionAlgorithm.cpp
- sources/Algo/src/GeneratorDefinitionAlgorithm.cpp
- sources/Algo/src/HVDCDefinitionAlgorithm.cpp
- sources/Context.cpp
- sources/Inputs/src/NetworkManager.cpp
- tests/algo/TestHvdcLineAlgo.cpp
adding dynamic models on hvdcs/generators which end up in a NaN in the jacobian
closes #711
> #711 only keep opened retained switches connected to shunts to avoid

- sources/Outputs/src/ParGenerator.cpp
- sources/Outputs/src/ParVRRemote.cpp
- sources/Outputs/src/Solver.cpp
- tests/outputs/reference/TestPar/TestPar.par
- tests/outputs/reference/TestParDynModel/TestParDynModel.par
- tests/outputs/reference/TestParRemote/TestParRemote.par
- tests/outputs/reference/TestParVRRemote/TestParVRRemote.par
- tests/outputs/reference/TestSolverPar/solver.par
- tests/outputs/reference/TestSolverParDefault/solver.par
- tests/outputs/reference/TestStartingPointMode/TestStartingPointModeFlatNoIRL.par
- tests/outputs/reference/TestStartingPointMode/TestStartingPointModeFlatWithIRL.par
- tests/outputs/reference/TestStartingPointMode/TestStartingPointModeWarmNoIRL.par
- tests/outputs/reference/TestStartingPointMode/TestStartingPointModeWarmWithIRL.par
> #716 update Frozen0 parameter name, remove bandwidth from reactive power

- sources/Outputs/src/ParVRRemote.cpp
> #716 remove useless log

- tests/main_n_sa/reference/launch/hvdcline_contingency/outputIIDM.xml
- tests/main_sa/reference/launch/hvdcline_contingency/outputIIDM.xml
> #722 Update references following DYN3049

- .github/workflows/ci.yml
> #726 Update java version for sonarcloud.

- sources/Outputs/src/DydHvdc.cpp
- sources/Outputs/src/ParHvdc.cpp
- tests/main/reference/hvdc_diagrams_flat_start/outputIIDM.xml
- tests/outputs/reference/TestDydDynModel/TestDydDynModel.dyd
- tests/outputs/reference/TestDydHvdc/TestDydHvdc.dyd
- tests/outputs/reference/TestDydVRRemote/TestDydVRRemote.dyd
- tests/outputs/reference/TestStartingPointMode/TestStartingPointModeFlatNoIRL.par
- tests/outputs/reference/TestStartingPointMode/TestStartingPointModeFlatWithIRL.par
> #720 Fix flat start mode depending on hvdc mode

- etc/Dictionaries/DFLError_en_GB.dic
- etc/Dictionaries/DFLLog_en_GB.dic
- sources/Context.h
- sources/Inputs/include/NetworkManager.h
- sources/Inputs/src/NetworkManager.cpp
- sources/main.cpp
- tests/inputs/TestNetworkManager.cpp
- tests/inputs/res/initial_conditions_NOK.iidm
- tests/inputs/res/initial_conditions_OK.iidm
- tests/inputs/res/initial_conditions_partially_OK.iidm
> #710 clean commit on a new branch based on PR #729

- .github/workflows/ci.yml
- .github/workflows/nightly-release.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- CMakeLists.txt
- documentation/dynaflow_launcher_documentation.sh
> #736 v1.7.0

- tests/main/res/config_launch_svc_regulation.json
> #739 fix typo in config_launch_svc_regulation.json

- sources/Inputs/include/HvdcLine.h
- sources/Inputs/include/Node.h
> #738 fix windows build

- .github/workflows/ci.yml
- .github/workflows/nightly-release.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- CMakeLists.txt
- documentation/dynaflow_launcher_documentation.sh
> #750 v1.6.1

- README.md
- documentation/README.md
- documentation/installation/installation.tex
- documentation/introduction/introduction.tex
> #752 update links following v1.6.0

- sources/Outputs/src/ParHvdc.cpp
> #759 use the proper abs method for vsc reactive limits

- .github/workflows/ci.yml
- .github/workflows/nightly-release.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
> #764 Fix node20 issues with old OS.

- CMakeLists.txt
- scripts/dynaflow-launcher.sh
- sources/main.cpp
> #762 allow to modify locale from dynawo core

- CMakeLists.txt
> #745 Fix cmake missing option.

- CMakeLists.txt
> #775 update iidm to v1.5.1

- tests/main_n_sa/reference/launch/generator_contingency/constraints.xml
- tests/main_n_sa/reference/launch/generator_network_contingency/constraints.xml
- tests/main_n_sa/reference/launch/static_var_compensator_contingency/constraints.xml
- tests/main_n_sa/reference/launch/two_windings_transformer_contingency/constraints.xml
- tests/main_sa/reference/launch/generator_contingency/constraints.xml
- tests/main_sa/reference/launch/generator_network_contingency/constraints.xml
- tests/main_sa/reference/launch/static_var_compensator_contingency/constraints.xml
- tests/main_sa/reference/launch/two_windings_transformer_contingency/constraints.xml
> #779 Update NRT references following DYN3262

- .github/workflows/nightly-release.yml
- .github/workflows/release.yml
> #777 Fix nightly release and release workflows.

- sources/Common/src/Log.cpp
> #792 Update following DYN-3244

- sources/Outputs/include/OutputsConstants.h
- sources/Outputs/include/ParCommon.h
- sources/Outputs/src/ParGenerator.cpp
- sources/Outputs/src/ParVRRemote.cpp
- tests/main/reference/distant_regulation/TestIIDM_distant_regulation.dyd
- tests/main/reference/distant_regulation/TestIIDM_distant_regulation.par
- tests/main/res/TestIIDM_distant_regulation.iidm
> #803 Add missing parameter when a nuclear generator is using infinite

- documentation/configuringDynaflowLauncher/DynaflowLaunchersInputFiles.tex
- scripts/envDFL.sh
> #761 add missing nsa option in help message of envDFL.sh

- tests/main/reference/hvdc_HvdcPV_HvdcPTanPhi/outputIIDM.xml
- tests/main/reference/hvdc_HvdcPV_HvdcPTanPhi_diagrams/outputIIDM.xml
> #806 update nrt references following issue 3464 in dynawo

- sources/Inputs/include/NetworkManager.h
- sources/Inputs/src/NetworkManager.cpp
- tests/algo/TestAlgoDynModel.cpp
- tests/algo/TestGeneratorsAlgo.cpp
- tests/algo/TestHvdcLineAlgo.cpp
- tests/algo/TestSlackNodeAlgo.cpp
> #798 Update following DYN-2455 (following Part. 2)

- .github/workflows/nightly-release.yml
- .github/workflows/release.yml
- sources/main.cpp
> #784 Nightly release and release without mpi

- sources/Context.cpp
> #788 dump results file for SA

- etc/xsd/assembling_dynaflow.xsd
- sources/Algo/include/HVDCDefinitionAlgorithm.h
- sources/Algo/src/HVDCDefinitionAlgorithm.cpp
- sources/Inputs/include/AssemblingDataBase.h
- sources/Inputs/include/HvdcLine.h
- sources/Inputs/src/AssemblingDataBase.cpp
- sources/Outputs/src/DydHvdc.cpp
- sources/Outputs/src/ParDynModel.cpp
- sources/Outputs/src/ParHvdc.cpp
- tests/algo/TestHvdcLineAlgo.cpp
- tests/algo/res/assembling_test_hvdc_side2.xml
- tests/inputs/TestAssemblingXmlDocument.cpp
- tests/inputs/res/assembling.xml
- tests/main/CMakeLists.txt
- tests/main/reference/hvdc_svc_side2/Network.par
- tests/main/reference/hvdc_svc_side2/TestIIDM_hvdc_svc_side2.dyd
- tests/main/reference/hvdc_svc_side2/TestIIDM_hvdc_svc_side2.par
- tests/main/reference/hvdc_svc_side2/constraints.xml
- tests/main/reference/hvdc_svc_side2/lostEquipments.xml
- tests/main/reference/hvdc_svc_side2/outputIIDM.xml
- tests/main/reference/hvdc_svc_side2/solver.par
- tests/main/res/TestIIDM_hvdc_svc_side2.iidm
- tests/main/res/assembling_svc_hvdc_side2.xml
- tests/main/res/config_hvdc_svc_side2.json
- tests/main/res/setting_svc_hvdc_side2.xml
- tests/outputs/TestDiagram.cpp
- tests/outputs/TestDyd.cpp
- tests/outputs/TestPar.cpp
the SVC is regulating for hvdcs
closes #815
> #815 Add the possibility to specify in the assembling the side of which

- sources/Outputs/include/DydCommon.h
- sources/Outputs/include/DydEvent.h
- sources/Outputs/src/DydDynModel.cpp
- sources/Outputs/src/DydEvent.cpp
- sources/Outputs/src/DydGenerator.cpp
- sources/Outputs/src/DydHvdc.cpp
- sources/Outputs/src/DydLoads.cpp
- sources/Outputs/src/DydSVarC.cpp
- sources/Outputs/src/DydVRRemote.cpp
- sources/Outputs/src/ParEvent.cpp
> #798 Update following DYN-2455 (following Part. 5)

- .github/workflows/ci.yml
- .github/workflows/nightly-release.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- CMakeLists.txt
- documentation/dynaflow_launcher_documentation.sh
> #821 v1.8.0

- .github/workflows/ci.yml
- .github/workflows/nightly-release.yml
- .github/workflows/release.yml
> #823 Windows workflows fix

- sources/Algo/include/GeneratorDefinitionAlgorithm.h
- sources/Algo/src/GeneratorDefinitionAlgorithm.cpp
- sources/Inputs/include/Behaviours.h
- sources/Inputs/src/NetworkManager.cpp
- sources/Outputs/include/ParGenerator.h
- sources/Outputs/src/ParGenerator.cpp
- tests/main/CMakeLists.txt
- tests/main/reference/launch_kGover/Network.par
- tests/main/reference/launch_kGover/TestIIDM_launch_kGover.dyd
- tests/main/reference/launch_kGover/TestIIDM_launch_kGover.par
- tests/main/reference/launch_kGover/outputIIDM.xml
- tests/main/reference/launch_kGover/solver.par
- tests/main/res/TestIIDM_launch_kGover.iidm
- tests/main/res/config_launch_kGover.json
> 814 get kgover information from data interface v17

- sources/main.cpp
> #810 flush DFL log before zipping

- sources/main.cpp
- tests/main_n_sa/reference/launch/generator_contingency/constraints.xml
- tests/main_n_sa/reference/launch/generator_network_contingency/constraints.xml
- tests/main_n_sa/reference/launch/static_var_compensator_contingency/constraints.xml
- tests/main_n_sa/reference/launch/two_windings_transformer_contingency/constraints.xml
- tests/main_n_sa/reference/launch_archive/generator_contingency/constraints.xml
- tests/main_n_sa/reference/launch_archive/generator_network_contingency/constraints.xml
- tests/main_n_sa/reference/launch_archive/static_var_compensator_contingency/constraints.xml
- tests/main_n_sa/reference/launch_archive/two_windings_transformer_contingency/constraints.xml
- tests/main_sa/reference/launch/generator_contingency/constraints.xml
- tests/main_sa/reference/launch/generator_network_contingency/constraints.xml
- tests/main_sa/reference/launch/static_var_compensator_contingency/constraints.xml
- tests/main_sa/reference/launch/two_windings_transformer_contingency/constraints.xml
- tests/main_sa/reference/launch_archive/generator_contingency/constraints.xml
- tests/main_sa/reference/launch_archive/generator_network_contingency/constraints.xml
- tests/main_sa/reference/launch_archive/static_var_compensator_contingency/constraints.xml
- tests/main_sa/reference/launch_archive/two_windings_transformer_contingency/constraints.xml
> #836 update nrt references following 3544 9OS

- sources/main.cpp
> #845 fix compile using gcc 11

- sources/Outputs/src/ParGenerator.cpp
- tests/main/reference/hvdc_svc/TestIIDM_hvdc_svc.par
- tests/main/reference/hvdc_svc_side2/TestIIDM_hvdc_svc_side2.par
- tests/main/reference/launch_svc/TestIIDM_launch_svc.par
- tests/main/reference/launch_svc_infinite/TestIIDM_launch_svc_infinite.par
- tests/main/reference/launch_svc_network/TestIIDM_launch_svc_network.par
- tests/main/reference/launch_svc_tfo/TestIIDM_launch_svc_tfo.par
- tests/main/reference/launch_svc_tfo_infinite/TestIIDM_launch_svc_tfo_infinite.par
- tests/main/res/setting_svc.xml
- tests/main/res/setting_svc_hvdc.xml
- tests/main/res/setting_svc_hvdc_side2.xml
- tests/outputs/reference/TestParDynModel/TestParDynModel.par
- tests/outputs/res/setting.xml
> 844 retrieve rpcl volatge limits values v17

- etc/Dictionaries/DFLLog_en_GB.dic
- sources/Algo/include/DynModelFilterAlgorithm.h
- sources/Algo/include/GeneratorDefinitionAlgorithm.h
- sources/Algo/include/HVDCDefinitionAlgorithm.h
- sources/Algo/src/DynModelFilterAlgorithm.cpp
- sources/Algo/src/HVDCDefinitionAlgorithm.cpp
- sources/Context.cpp
- tests/algo/TestDynModelFilterAlgo.cpp
- tests/algo/TestHvdcLineAlgo.cpp
- tests/main/CMakeLists.txt
- tests/main/reference/hvdc_svc_off/TestIIDM_hvdc_svc_off.dyd
- tests/main/reference/hvdc_svc_off/outputIIDM.xml
- tests/main/res/TestIIDM_hvdc_svc_off.iidm
- tests/main/res/config_hvdc_svc_off.json
> #852 remove hvdc from svc if vsc voltage regulation is off

- sources/Inputs/src/AssemblingDataBase.cpp
- sources/Inputs/src/SettingDataBase.cpp
- tests/inputs/CMakeLists.txt
> #854 remove useless warning when xsd validation is disabled

- tests/main/reference/hvdc_svc/outputIIDM.xml
> #858 update nrt following OS 3546 part 2

- tests/main/reference/hvdc_svc/constraints.xml
> #858 update nrt references

- tests/main/reference/hvdc_svc/constraints.xml
- tests/main/reference/hvdc_svc/outputIIDM.xml
> #858 update nrt following os 3546 part 2 v17

- README.md
> #864 Update list of maintainers

- documentation/configuringDynaflowLauncher/DynaflowLaunchersInputFiles.tex
- documentation/resources/syntaxExample/config.json
- sources/Inputs/include/Configuration.h
- sources/Inputs/src/Configuration.cpp
- sources/Outputs/include/Solver.h
- sources/Outputs/src/Solver.cpp
- tests/inputs/TestConfig.cpp
- tests/inputs/res/config.json
- tests/inputs/res/config_N.json
- tests/inputs/res/config_SA.json
- tests/inputs/res/config_SA_2.json
> #870 add an option to define the minimal time step for the solver

- documentation/configuringDynaflowLauncher/DynaflowLaunchersInputFiles.tex
- sources/Inputs/src/Configuration.cpp
> #873 Allow defining an initial dump state in N

- .github/workflows/ci.yml
- .github/workflows/nightly-release.yml
- .github/workflows/release.yml
- CMakeLists.txt
- README.md
> #877 update windows ci to windos server 2022

- sources/Outputs/src/ParDynModel.cpp
found (to avoid failing with optional connections)
close #882
> #882 Always dump count parameters from setting even if no component was

- .github/workflows/ci.yml
- .github/workflows/nightly-release.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- CMakeLists.txt
- documentation/dynaflow_launcher_documentation.sh
> #888 v1.7.1

- README.md
- documentation/README.md
- documentation/installation/installation.tex
- documentation/introduction/introduction.tex
> #890 Update documentation following release v1.7.0
